# Generated by Django 4.2.13 on 2024-06-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('MSMC', 'Multi select Multiple Choice'), ('TF', 'True or False')], default='MC', max_length=4),
        ),
    ]
